#ifndef QTTEMPLATEINTERPRETERVERSION_H
#define QTTEMPLATEINTERPRETERVERSION_H

#define QT_TEMPLATE_INTERPRETER_VERSION_STR "1.2.0"
/*
   QT_TEMPLATE_INTERPRETER_VERSION is (major << 16) + (minor << 8) + patch.
*/
#define QT_TEMPLATE_INTERPRETER_VERSION 0x010200
/*
   can be used like #if (QT_TEMPLATE_INTERPRETER_VERSION >= QT_TEMPLATE_INTERPRETER_VERSION_CHECK(1, 0, 1))
*/
#define QT_TEMPLATE_INTERPRETER_VERSION_CHECK(major, minor, patch) ((major << 16) | (minor << 8) | (patch))

#endif // QTTEMPLATEINTERPRETERVERSION_H
